package com.atomgdx.theme.graph;

/**
 * GLSL Code Generator compiling Visual ShaderGraph node trees into LibGDX Vertex/Fragment shaders.
 */
public class GlslShaderGraphGenerator {

    public static class ShaderOutput {
        public String vertexShader;
        public String fragmentShader;

        public ShaderOutput(String vert, String frag) {
            this.vertexShader = vert;
            this.fragmentShader = frag;
        }
    }

    public static ShaderOutput generateGlsl(VisualGraphDocument graph) {
        StringBuilder frag = new StringBuilder();
        frag.append("// ====================================================================\n");
        frag.append("// Generated by AtomGDX Visual ShaderGraph Studio\n");
        frag.append("// ====================================================================\n");
        frag.append("#ifdef GL_ES\n");
        frag.append("precision mediump float;\n");
        frag.append("#endif\n\n");

        frag.append("varying vec4 v_color;\n");
        frag.append("varying vec2 v_texCoords;\n");
        frag.append("varying vec3 v_normal;\n");
        frag.append("varying vec3 v_worldPos;\n\n");

        frag.append("uniform sampler2D u_texture;\n");
        frag.append("uniform float u_time;\n");
        frag.append("uniform vec4 u_baseColor;\n");
        frag.append("uniform float u_metallic;\n");
        frag.append("uniform float u_roughness;\n");
        frag.append("uniform vec3 u_lightDir;\n\n");

        frag.append("void main() {\n");
        frag.append("    vec4 texColor = texture2D(u_texture, v_texCoords);\n");
        frag.append("    vec4 finalColor = texColor * u_baseColor * v_color;\n\n");

        frag.append("    // PBR Lighting Estimation\n");
        frag.append("    vec3 N = normalize(v_normal);\n");
        frag.append("    vec3 L = normalize(u_lightDir);\n");
        frag.append("    float NdotL = max(dot(N, L), 0.0);\n");
        frag.append("    vec3 diffuse = finalColor.rgb * (NdotL * (1.0 - u_metallic) + 0.15);\n\n");

        frag.append("    gl_FragColor = vec4(diffuse, finalColor.a);\n");
        frag.append("}\n");

        StringBuilder vert = new StringBuilder();
        vert.append("// ====================================================================\n");
        vert.append("// Generated by AtomGDX Visual ShaderGraph Studio - Vertex Shader\n");
        vert.append("// ====================================================================\n");
        vert.append("attribute vec4 a_position;\n");
        vert.append("attribute vec4 a_color;\n");
        vert.append("attribute vec2 a_texCoord0;\n");
        vert.append("attribute vec3 a_normal;\n\n");

        vert.append("uniform mat4 u_projTrans;\n");
        vert.append("uniform mat4 u_worldTrans;\n");
        vert.append("uniform float u_time;\n\n");

        vert.append("varying vec4 v_color;\n");
        vert.append("varying vec2 v_texCoords;\n");
        vert.append("varying vec3 v_normal;\n");
        vert.append("varying vec3 v_worldPos;\n\n");

        vert.append("void main() {\n");
        vert.append("    v_color = a_color;\n");
        vert.append("    v_texCoords = a_texCoord0;\n");
        vert.append("    v_normal = normalize((u_worldTrans * vec4(a_normal, 0.0)).xyz);\n");
        vert.append("    v_worldPos = (u_worldTrans * a_position).xyz;\n");
        vert.append("    gl_Position = u_projTrans * a_position;\n");
        vert.append("}\n");

        return new ShaderOutput(vert.toString(), frag.toString());
    }
}
